services:
	- type: web
		name: house-price-prediction-model-posc
		env: python
		buildCommand: pip install -r requirements.txt
		startCommand: gunicorn -w 2 -k gthread --timeout 180 --log-level info --bind 0.0.0.0:$PORT app:app
		autoDeploy: true
